### ISSUE TITLE
adding new NaN item to inventories

### ISSUE THREAD

**Issue by Rbutchko** [justingolden21/Econ-Sim#2]
Features first on bankrupt firms, then spreads.

**Comment by justingolden21** [comment]
Not true, shows up even if bankruptcy is turned off.

**Comment by Rbutchko** [comment]
It will also occur on non bankrupt firms, but in my testing it seemed to most often start with bankrupt smiths. When I changed the values to make them more competitive, then the first to exhibit the glitch were mills. Bankruptcy was never a requirement, it just seems to show first in the firms that had the hardest time.

**Comment by justingolden21** [comment]
resolved
